snap: migrate to `base: core24`
MirServer/mir-test-tools pull request #70
Opened 2024-01-29 16:47 UTC by Saviq

2024-04-25 09:04 UTC, AlanGriffiths requested changes
Consolidating the plugs & slots does avoid some repetition, but makes it less clear why each is required. That might matter if we come to clear things up. (It's a fairly balanced trade off - I can be persuaded.)

2024-04-25 09:04 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +grade: devel
I *think* if we use snapcraft 8.2 (currently `beta`) we can avoid all this "devel" hacking

2024-04-25 09:04 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +      - gpu-2404
We (need to) have `gpu-2404` as a global plug, I don't think we need it here too.

2024-04-25 09:12 UTC, Saviq reviewed
> Consolidating the plugs & slots does avoid some repetition, but makes it less clear why each is required. That might matter if we come to clear things up. (It's a fairly balanced trade off - I can be persuaded.)

You mean rather than in "global" `plugs:`? Yeah, I learned that's not to be used that way… check e.g. [mir-test-tools-22-edge](https://launchpad.net/~mir-team/+snap/mir-test-tools-22-edge):
```
Warning: implicit plug assignment in 'login-session-control', 'opengl', and 'x11'. Plugs should be assigned to the app to which they apply, and not implicitly assigned via the global 'plugs:' stanza which is intended for configuration only.
(Reference: https://snapcraft.io/docs/snapcraft-interfaces)
Warning: implicit slot assignment in 'wayland'. Slots should be assigned to the app to which they apply, and not implicitly assigned via the global 'slots:' stanza which is intended for configuration only.
(Reference: https://snapcraft.io/docs/snapcraft-interfaces)
```

2024-04-25 09:12 UTC, Saviq commented on snap/snapcraft.yaml
> +      - gpu-2404
You'd think… but check e.g. [mir-test-tools-22-edge](https://launchpad.net/~mir-team/+snap/mir-test-tools-22-edge):
```
Warning: implicit plug assignment in 'login-session-control', 'opengl', and 'x11'. Plugs should be assigned to the app to which they apply, and not implicitly assigned via the global 'plugs:' stanza which is intended for configuration only.
(Reference: https://snapcraft.io/docs/snapcraft-interfaces)
Warning: implicit slot assignment in 'wayland'. Slots should be assigned to the app to which they apply, and not implicitly assigned via the global 'slots:' stanza which is intended for configuration only.
(Reference: https://snapcraft.io/docs/snapcraft-interfaces)
```

2024-04-25 09:12 UTC, Saviq commented on snap/snapcraft.yaml
> +grade: devel
But I can't get that for the CI builds…

https://bugs.launchpad.net/snapcraft/+bug/2061517

2024-04-25 09:35 UTC, AlanGriffiths commented
> You mean rather than in "global" `plugs:`?

No, I mean shared (by anchors) across all the apps

2024-04-25 09:39 UTC, Saviq commented
> No, I mean shared (by anchors) across all the apps

Ah. Well, if we could stick to global plugs like we had them, yeah - but because that's not The Way™, the only other option is enumerating them all… and yes, on the one hand we only had e.g. `pulseaudio` apply to the SDL app, not all of them. We might need someone else to convince us one way or the other.

2024-04-25 09:42 UTC, Saviq commented on snap/snapcraft.yaml
> +      - gpu-2404
Except…
https://snapcraft.io/docs/snapcraft-top-level-metadata#heading--plugs-and-slots-for-an-entire-snap

> Plugs and slots for an [interface](https://snapcraft.io/docs/supported-interfaces) are usually configured per-app or per-daemon within snapcraft.yaml. See [Snapcraft app metadata](https://snapcraft.io/docs/snapcraft-app-and-service-metadata) for more details. However, snapcraft.yaml also enables global plugs and slots configuration for an entire snap:

> `plugs`
> Type: dict (optional)
> These plugs apply to all apps …

2024-04-25 10:19 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +      - gpu-2404
When code and documentation disagree, trust neither

2024-05-06 12:00 UTC, Saviq commented on snap/snapcraft.yaml
> +      - gpu-2404
The documentation was updated to match code.

2024-05-08 09:56 UTC, Saviq commented
@AlanGriffiths this can land now, ARM builds will fail until https://github.com/canonical/snapcraft/pull/4786 makes its way into stable.

2024-05-08 11:16 UTC, AlanGriffiths commented on .github/workflows/snap.yml
> +        snapcraft-channel: edge
Really?

2024-05-08 11:17 UTC, Saviq commented on .github/workflows/snap.yml
> +        snapcraft-channel: edge
Just for a couple of days ;)

2024-05-08 11:20 UTC, AlanGriffiths approved these changes
> Just for a couple of days ;)

OK then

2024-05-08 11:33 UTC, merged