Use ppa plugin to access PPAs
MirServer/mir-test-tools pull request #8
Opened 2019-08-30 15:41 UTC by AlanGriffiths

2019-09-12 14:50 UTC, wmww requested changes

2019-09-12 14:50 UTC, wmww commented on snap/plugins/ppa.py
> +        for ppa in self.options.ppa.split(" "):
Why are you parsing a space separated list of PPAs, instead of an actual YAML list?

2019-09-12 15:05 UTC, AlanGriffiths commented on snap/plugins/ppa.py
> +        for ppa in self.options.ppa.split(" "):
Mostly because the "normal" case is a single PPA.

2019-09-12 15:35 UTC, wmww commented on snap/plugins/ppa.py
> +        for ppa in self.options.ppa.split(" "):
IMO it should either support a single PPA and be a string, or support multiple PPAs and be a list.

2019-09-13 16:11 UTC, wmww approved these changes
LGTM
bors r+

2019-09-13 16:13 UTC, merged

2019-09-13 16:13 UTC, AlanGriffiths commented
> bors r+

@wmww It's a snap recipe, there's no bors.